### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Xaleth** [Mayeu/gpg.conf#1]
For the default key, do I insert my public keyid, or my private keyid?

Regarding the default-preference-list, is the RSA algorithm an option? From what I've heard, RSA is definitely stronger that SHA512.

I'm new to using GNUPG so please take it easy.

**Comment by Mayeu** [comment]
Hello,

Thanks for considering this project, but it is unmaintainned and surelly pretty outdated (4 year old), so please don't use it and refer to the [original source](https://riseup.net/en/security/message-security/openpgp/best-practices). I will mark this project as archived after writting this comment.

> Regarding the default-preference-list, is the RSA algorithm an option? From what I've heard, RSA is definitely stronger that SHA512.

RSA is a public key algorithm, and SHA512 a hashing algorithm. Those don't have the same purpose so you can't exchange one for another.

Finally, please strongly consider **not using** GPG at all. There [are better and safer alternative](https://twitter.com/tqbf/status/950147735583326208) for communication.

Good luck :)
